### ISSUE TITLE
Can't reproduce results

### ISSUE THREAD

**Issue by DLuminary** [daniel-om-weber/riann#1]
Hi Daniel and thanks for sharing your work.

I have been trying to use your code on some self measurements, but the results seem to be far off reality. 
So then I have been trying to do a test run on some random samples from OxIOD dataset, and again I have failed to reproduce anything remotely accurate. Is there something wrong with the uploaded model? or am I using the code incorrectly?

Could you please provide a working example, and perhaps a more detailed readme (what units to use for the acce/gyro data, is it linear acceleration being used or total acceleration, etc)? 

Thanks again.

**Comment by daniel-om-weber** [comment]
Thank you for your interest in our work. At the moment I am on vacation but maybe some more detailed information about the expected measurement data, extracted from the code comments with the units, can help you. 
acc: numpy-array [sequence_length x 3]         Acceleration data of the IMU [m/s^2]. The axis order is x,y,z.        
gyr: numpy-array [sequence_length x 3]            Gyroscope data of the IMU [rad/s]. The axis order is x,y,z.        
fs: float            Samplingrate of the provided IMU data [Hz]

In a few days, I will be back and then I will provide a more detailed example in a jupyter notebook.

**Comment by DLuminary** [comment]
Thanks for your rapid reply.

I have been assuming that the quaternion order is w,x,y,z. Is this correct?
And is it the total acceleration, i.e. gravity + linear acceleration, being used?

Enjoy your vacation! I shall be waiting patiently for an example.

Thanks

**Comment by daniel-om-weber** [comment]
Yes, the quaternion order is w,x,y,z just as described in the paper. The acceleration used is the one directly measured from the IMU, i.e. gravity + linear acceleration.

**Comment by daniel-om-weber** [comment]
In the repository, you will find now an example of the application of RIANN to the BROAD dataset, that has been used in the RIANN paper. I hope you will find this helpful.

**Comment by DLuminary** [comment]
@daniel-om-weber many thanks. Indeed this was helpful.

An additional question if I may. How is RIANN determining the heading (yaw), is it just random?

Thanks

**Comment by daniel-om-weber** [comment]
The optimization function of the neural network ignores the heading of the target orientation which results in a not defined heading. In future work, the inclusion of a magnetometer would enable the estimation of the heading as well.
